version: '3'

services:
  raft_node_3:
    container_name: raft_node_3
    image: raft_node
    build:
      context: .
      dockerfile: RaftNode/Dockerfile
    ports:
      - 8503:8080
    environment:
      - NODES=http://144.17.92.13:8501,http://144.17.92.13:8502
