name: Distributed Raft App
run-name: ${{ github.actor }} is deploying 🚀
on: [push]

jobs:
  Test:
    runs-on: office-3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'
      - name: Run tests
        run: dotnet test RaftTests

  Build:
    needs: Test
    runs-on: office-3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build 

  Build2:
    needs: Test
    runs-on: office-2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose2.yml build 

  Deploy:
    needs: Build
    runs-on: office-3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
  
      - name: Deploy on machine
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d

  Deploy2:
    needs: Build2
    runs-on: office-2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
  
      - name: Deploy on machine
        run: |
          docker-compose -f docker-compose2.yml down
          docker-compose -f docker-compose2.yml up -d
          
  